_merge = "deep"

languageCode = 'fr-fr'
title = 'Direction générale de la mondialisation'

[module]
[[module.imports]]
path = 'github.com/disic/frago'

[outputs]
 home    = ["HTML","JSON"]
 page    = ["HTML","JSON","declaration","declarationpage","accessibility","accessibilitypage","recommendation", "recommendationpage","performance","performancepage"]

[params]
organisation = "Direction générale de la mondialisation"
robots = "noindex, nofollow"